version: '2'

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - appRoot:/usr/share/serviceOnlyContainers
            - ../var/log:/var/log
            - ./nginx/root_home/.ash_history:/root/.ash_history
        ports:
            - "8082:80"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        networks:
          backend:
            aliases:
              - service-only-containers.adam-cameron
        extra_hosts:
            - "service-only-containers.adam-cameron:127.0.0.1"
        depends_on:
              - "php-fpm"

    php-fpm:
        build:
            context: ./php-fpm
        volumes:
            - appRoot:/usr/share/serviceOnlyContainers
            - ./php-fpm/root_home/.bash_history:/root/.bash_history
        stdin_open: true
        tty: true
        networks:
            - backend
            
    ssh:
        image:
            jeroenpeeters/docker-ssh
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        environment:
            - CONTAINER=serviceonlycontainers_php-fpm_1
            - AUTH_MECHANISM=noAuth
        ports:
            - "2222:22"

volumes:
    appRoot:

networks:
  backend:
    driver: "bridge"
    